ScreenManager:

    LoginScreen:
        name: "login"

    PrincipalScreen:
        name: "principal"

    PerfilScreen:
        name: "perfil"


<LoginScreen>:
    md_bg_color: app.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: "vertical"
        padding: "50dp"
        spacing: "20dp"
        theme_text_color: "Primary"

        Widget:
            size_hint_y: 0.25

        MDLabel:
            text: "Marketplace UCT"
            halign: "center"
            font_style: "Headline"
            theme_text_color: "Primary"
            size_hint_y: None
            height: "60dp"
        
        MDScrollView: 
            MDBoxLayout:
                orientation: "vertical"
                spacing: "15dp"
                adaptive_height: True

                MDLabel:
                    text: "Compra, vende e intercambia dentro de la comunidad universitaria"
                    halign: "center"
                    theme_text_color: "Secondary"
                    size_hint_y: None
                    height: "60dp"

                MDTextField:
                    id: nombre
                    mode: "outlined"
                    size_hint_x: 0.9
                    pos_hint: {"center_x": 0.5}

                    MDTextFieldHintText:
                        text: "Ingresa tu nombre"

                Widget:
                    size_hint_y: 0.05

                MDButton:
                    style: "tonal"
                    pos_hint: {"center_x": 0.5}
                    size_hint_x: 0.7
                    on_release: root.ingresar()

                    MDButtonText:
                        text: "Ingresar"

                Widget:
                    size_hint_y: 0.3


<PrincipalScreen>:
    md_bg_color: app.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: "vertical"
        theme_text_color: "Primary"

        MDTopAppBar:
            type: "small" 
            size_hint_y: None
            theme_bg_color: "Custom"
            md_bg_color: app.theme_cls.secondaryContainerColor
            height: "84dp"
            MDTopAppBarTitle:
                text: "Marketplace UCT"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "account"
                    on_release: root.manager.current = "perfil"

                MDActionTopAppBarButton:
                    icon: "logout"
                    on_release: root.manager.current = "login"
        MDScrollView:
            MDBoxLayout:
                orientation: "vertical"
                spacing: "15dp"
                padding: "50dp"
                adaptive_height: True

                MDLabel:
                    id: bienvenida
                    text: "Bienvenido"
                    font_style: "Title"
                    theme_text_color: "Primary"
                    size_hint_y: None
                    height: "40dp"

                MDTextField:
                    mode: "outlined"
                    size_hint_x: 0.9
                    pos_hint: {"center_x": 0.5}

                    MDTextFieldLeadingIcon:
                        icon: "magnify"

                    MDTextFieldHintText:
                        text: "Buscar productos..."

                MDLabel:
                    text: "Publicaciones recientes"
                    font_style: "Title"
                    theme_text_color: "Primary"
                    size_hint_y: None
                    height: "50dp"

                MDCard:
                    style: "elevated"
                    orientation: "vertical"
                    padding: "15dp"
                    spacing: "5dp"
                    size_hint_y: None
                    height: "150dp"
                    theme_shadow_offset: "Custom"
                    shadow_offset: (1, -2)
                    theme_shadow_softness: "Custom"
                    shadow_softness: 8
                    theme_elevation_level: "Custom"
                    elevation_level: 2

                    MDLabel:
                        text: "iPhone 12"
                        font_style: "Title"

                    MDLabel:
                        text: "$250.000"

                    MDLabel:
                        text: "Publicado por estudiante UCT"

                MDCard:
                    style: "elevated"
                    orientation: "vertical"
                    padding: "15dp"
                    spacing: "5dp"
                    size_hint_y: None
                    height: "150dp"
                    theme_shadow_offset: "Custom"
                    shadow_offset: (1, -2)
                    theme_shadow_softness: "Custom"
                    shadow_softness: 8
                    theme_elevation_level: "Custom"
                    elevation_level: 2

                    MDLabel:
                        text: "Libros de cálculo"
                        font_style: "Title"

                    MDLabel:
                        text: "$15.000"

                    MDLabel:
                        text: "Publicado por estudiante UCT"



<PerfilScreen>:
    md_bg_color: app.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: "vertical"

        # 1. Barra superior (igual que ya tienes)
        MDTopAppBar:
            type: "small"
            size_hint_y: None
            theme_bg_color: "Custom"
            md_bg_color: app.theme_cls.secondaryContainerColor
            height: "84dp"

            MDTopAppBarTitle:
                text: "Mi Perfil"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "arrow-left"
                    on_release: root.manager.current = "principal"

                MDActionTopAppBarButton:
                    icon: "logout"
                    on_release: root.manager.current = "login"

     
        MDScrollView:
            MDBoxLayout:
                orientation: "vertical"
                spacing: "20dp"
                padding: "30dp"
                adaptive_height: True

         
                MDCard:
                    style: "outlined"
                    orientation: "vertical"
                    padding: "20dp"
                    spacing: "25dp"
                    size_hint_y: None
                    adaptive_height: True
                    pos_hint: {"center_x": 0.5}

      
                    MDBoxLayout:
                        orientation: "horizontal"
                        size_hint_y: None
                        height: "48dp"

                        Widget:

                        MDIconButton:
                            icon: "cog"
                            theme_icon_color: "Primary"

                    MDCard:
                        size_hint: None, None
                        size: "100dp", "100dp"
                        radius: [50,]
                        pos_hint: {"center_x": 0.5}
                        theme_bg_color: "Custom"
                        md_bg_color: 0.6, 0.6, 0.6, 1
                        elevation_level: 0

                        AnchorLayout:
                            anchor_x: "center"
                            anchor_y: "center"

                            MDIconButton:
                                icon: "account"
                                icon_size: "60sp"
                                theme_icon_color: "Custom"
                                icon_color: 1, 1, 1, 1

                    MDLabel:
                        id: nombre_perfil
                        text: "Usuario"
                        halign: "center"
                        font_style: "Headline"
                        theme_text_color: "Primary"
                        size_hint_y: None
                        height: "50dp"

                    MDButton:
                        style: "tonal"
                        theme_bg_color: "Custom"
                        md_bg_color: app.theme_cls.secondaryContainerColor
                        pos_hint: {"center_x": 0.5}
                        size_hint_x: 0.8

                        MDButtonText:
                            text: "Mis publicaciones"
                            theme_text_color: "Custom"
                            text_color: app.theme_cls.onSecondaryContainerColor

                    MDCard:
                        style: "elevated"
                        orientation: "vertical"
                        padding: "15dp"
                        spacing: "5dp"
                        size_hint_y: None
                        height: "150dp"
                        theme_shadow_offset: "Custom"
                        shadow_offset: (1, -2)
                        theme_shadow_softness: "Custom"
                        shadow_softness: 8
                        theme_elevation_level: "Custom"
                        elevation_level: 2

                        MDLabel:
                            text: "iPhone 12"
                            font_style: "Title"

                        MDLabel:
                            text: "$250.000"

                        MDLabel:
                            text: "Publicado por estudiante UCT"
                    
                    Widget:
                        size_hint_y: 0.1

